[package]
name = "hd2-aboba"
version = "0.1.0"
edition = "2024"

[dependencies]
enigo = "0.2.0"
rdev = "0.5.2"
time = { version = "0.3.47", features = ["local-offset", "macros", "serde"] }
chrono = "0.4.43"
once_cell = "1.21.3"